#!/bin/bash
# Wrapper for dsync to be called from cron

# First, set up my environment
export HOME=/home/dang
source ${HOME}/.keychain/${HOSTNAME}-sh

DFGcleanup() {
	echo "$(date): $@" >> ${HOME}/tmp/dsync.timestamps
}

# Standard functions
source ${SCRIPTS}/functions.sh

echo "$(date) begin dsync" >> ${HOME}/tmp/dsync.timestamps
# Sync portage
${SCRIPTS}/dsync -v > ${HOME}/tmp/dsync.log 2>&1 || die "dsync failed"
date >> ${HOME}/tmp/dsync.timestamps
