#!/bin/bash

# Set usage output
USAGE="[-hcfov]"
LONGUSAGE="\t-h\tPrint this help message
\t-c\tSkip regen of system cscope
\t-f\tFast update (no metadata regen)
\t-o\tSkip updating overlays
\t-v\tBe verbose"

# Standard functions
source ${SCRIPTS}/functions.sh

ECVSUPARGS=""
# Parse arguments
while getopts ":hcfov" option; do
       case ${option} in
               c ) NOSYSCSCOPE="y";;
               f ) ECVSUPARGS="${ECVSUPARGS} -f";;
               o ) ECVSUPARGS="${ECVSUPARGS} -n";;
               v ) ECVSUPARGS="${ECVSUPARGS} -v";;
               h ) usage;;
               \? ) usage "Invalid argument ${OPTARG}";;
               * ) usage "Invalid argument ${option}";;
       esac
done

if [ "${OPTIND}" != "0" ]; then
       shift $((OPTIND-1))
fi

${SCRIPTS}/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
sudo cp /var/cache/eix/portage.eix /var/cache/eix/previous.eix || die "Error while copying cache-file to a save location."
sudo eix-update                         || die "Problems with eix-update."
sudo eix-diff /var/cache/eix/previous.eix || die "Error while diffing."
if [ -z "${NOSYSCSCOPE}" ]; then
	cd /usr/src/debug
	sudo ${SCRIPTS}/maketags -k
fi
exit 0
