#!/bin/bash

# Set usage output
USAGE="[-hfn]"
LONGUSAGE="\t-h\tPrint this help message
\t-c\tSkip regen of system cscope
\t-f\tFast update (no metadata regen)
\t-o\tSkip updating overlays"

# Standard functions
source ${HOME}/.scripts/functions.sh

ECVSUPARGS=""
# Parse arguments
while getopts ":hfn" option; do
       case ${option} in
               c ) NOSYSCSCOPE="y";;
               f ) ECVSUPARGS="${ECVSUPARGS} -f";;
               o ) ECVSUPARGS="${ECVSUPARGS} -n";;
               h ) usage;;
               \? ) usage "Invalid argument ${OPTARG}";;
               * ) usage "Invalid argument ${option}";;
       esac
done

if [ "${OPTIND}" != "0" ]; then
       shift $((OPTIND-1))
fi

${HOME}/.scripts/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
tmpfile=$(mktemp)
sudo cp /var/cache/eix ${tmpfile} || die "Error while copying cache-file to a save location."
sudo update-eix                         || die "Problems with update-eix."
sudo diff-eix ${tmpfile} || die "Error while diffing."
sudo rm -f ${tmpfile} || die "Couldn't remove ${tmpfile}"
if [ -z "${NOSYSCSCOPE}" ]; then
	cd /usr/src/debug
	sudo ${HOME}/.scripts/maketags -k
fi
exit 0
