#!/bin/bash
# Wrapper for dsync to be called from cron

# First, set up my environment
export HOME=/home/dang
source ${HOME}/.profile

# Standard functions
source ${HOME}/.scripts/functions.sh

# Sync portage
${HOME}/.scripts/dsync || die "dsync failed"
date >> ${HOME}/tmp/dsync.timestamps
