#!/bin/bash
# Author: Emil Beinroth <emilbeinroth@gmx.net>

###########################################################################
#   eix is a small utility for searching ebuilds in the                   #
#   Gentoo Linux portage system. It uses indexing to allow quick searches #
#   in package descriptions with regular expressions.                     #
#                                                                         #
#   https://sourceforge.net/projects/eix                                  #
#                                                                         #
#   Copyright (c)                                                         #
#     Wolfgang Frisch <xororand@users.sourceforge.net>                    #
#     Emil Beinroth <emilbeinroth@gmx.net>                                #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
###########################################################################

source /sbin/functions.sh

GNOME_OVERLAY="/home/portage/overlays/gnome"

function die() {
	eerror "$@"
	exit 1
}

[ "${#}" -ne 0 ] && {
	usage ""
}

/home/dang/bin/ecvsup || die "Error during ecvsup"
tmpfile=$(mktemp)
sudo cp /var/cache/eix ${tmpfile} || die "Error while copying cache-file to a save location."
sudo update-eix                         || die "Problems with update-eix."
sudo diff-eix ${tmpfile} || die "Error while diffing."
sudo rm -f ${tmpfile} || die "Couldn't remove ${tmpfile}"
exit 0
