#!/bin/bash
#
# Bump a package in an overlay
#

# Portage functions
source ${HOME}/bin/scripts/portage-functions.sh

#
# Default Local parameters
# Remove old versions?
RMOLD="yes"

# Set usage output
USAGE="[-hpI][-m <commitmsg>] [<commitmsg>]"
LONGUSAGE="\t-h\tPrint this help message
\t-p\tPretend; don't actually commit.
\t-m <commitmsg>\tCommit message.
\t-I\tIgnore arches; pass -I to repoman.
\t<commitmsg>\tCommit message.  Overrides -m"

# Standard functions
source ${HOME}/bin/scripts/functions.sh

# Parse arguments
while getopts ":hpIm:" option; do
	case ${option} in
		p ) PRETEND="yes";;
		I ) VCS_REPOMAN_OPTS="-I";;
		m ) VCS_COMMITMSG=${OPTARG};;
		h ) usage;;
		\? ) usage "Invalid argument ${OPTARG}";;
		* ) usage "Invalid argument ${option}";;
	esac
done

if [ "${OPTIND}" != "0" ]; then
	shift $((OPTIND-1))
fi

if [ -n "$*" ]; then
	VCS_COMMITMSG="$*"
fi

if [ -z "${VCS_COMMITMSG}" ]; then
	usage "No commit message"
fi

vcs_detect
PWD=`pwd`

if [ -n "${PRETEND}" ]; then
	echo "committing ${PWD} with message \"${VCS_COMMITMSG}\""
	vcs_status
	exit
fi

vcs_update_check_conflicts
EBUILDS=`vcs status | grep ebuild | awk '{print $2}'`
if [ "${VCS}" == "cvs" ]; then
	echangelog "${VCS_COMMITMSG}" || die "echangelog died"
else
	echangelog-tng "${VCS_COMMITMSG}" || die "echangelog died"
fi
for i in ${EBUILDS}; do
	ebuild $i digest || die "digest failed"
done
vcs_commit

# Tell user we're done
#notify-send -t 0 "Done" "${NEWEBUILD}"
