#!/bin/bash
#
# Sync portage tree via CVS
#

source ${HOME}/bin/scripts/functions.sh

cd /usr/portage || die "no /usr/portage"
# Removed -C, because it touches mtime of every file, causing a full regen
cvs -q up -PdA || die "cvs up failed"
find /usr/portage -name '.#*' -exec rm {} \; || die "find .#* failed"
cd /home/portage/overlays/dangtopia/ || die "no dangtopia"
svn up || die "svn up of dangtopia failed"
cd /home/portage/overlays/gnome/ || die "no gnome"
svn up || die "svn up of gnome failed"
sudo emerge --regen || die "emerge regen failed"
sudo emerge --metadata || die "emerge metadata failed"
