#!/bin/bash
#
# Script that runs a test emerge from clean
#

# Set usage output
USAGE="[-h |--help] <atom>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t<atom>\n\t\tDepend atom to emerge"

# Standard functions
source ${HOME}/.scripts/functions.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o h --long help -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal

PACKAGE=$1
CHROOT_BASE="/opt/chroots"
CHROOT_NAME="gnome"

cd ${CHROOT_BASE} || die "no ${CHROOT_BASE}"

# clean up
echo "Testing ${PACKAGE}"
dchroot ${CHROOT_NAME} stop
sudo rm -rf ${CHROOT_NAME}
sudo tar xjf ${CHROOT_NAME}-current.tar.bz2
dchroot -d ${CHROOT_NAME} start
dchroot ${CHROOT_NAME} run -- emerge -v ${PACKAGE}
retval=$?
if [ "${retval}" == "0" ]; then
	echo "emerge ${PACKAGE} succeeded"
else
	echo "emerge ${PACKAGE} failed"
fi

dchroot ${CHROOT_NAME} stop

exit ${retval}
