#!/bin/bash
#
# Script that starts a named session of luakit
#

# Set usage output
USAGE="[-h |--help] <session>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t<session>\n\t\tName of session."

# Standard functions
source ${SCRIPTS}/functions.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o h --long help -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal
if [ -z "$1" ]; then
	usage "Must give session name"
fi

SESSION="$1"

OLD_DATA="${XDG_DATA_HOME:-${HOME}/.local/share}"
OLD_CACHE="${XDG_CACHE_HOME:-${HOME}/.cache}"

export XDG_DATA_HOME=${OLD_DATA}/sessions/${SESSION}/
export XDG_CACHE_HOME=${OLD_CACHE}/sessions/${SESSION}/

if [ ! -d "${XDG_DATA_HOME}" ]; then
	mkdir -p "${XDG_DATA_HOME}/luakit"
	mkdir -p "${XDG_CACHE_HOME}"
	ln -s "${OLD_DATA}/luakit/scripts" "${XDG_DATA_HOME}/luakit/scripts"
	echo "'# Config for the ${SESSION} session" > "${XDG_DATA_HOME}/config.sh"
fi

source "${XDG_DATA_HOME}/config.sh"

# Update adblock
#${HOME}/.config/luakit/plugins/tools/adblock-update.sh
#cd "${XDG_DATA_HOME}/luakit"
#pwd
#wget -N https://easylist-downloads.adblockplus.org/easylist.txt
#cd -

luakit -U
