#!/bin/bash
#
# Recursively make tags file for all c, cpp, C, c++, h files
#

USAGE="[-hk] [<directories>]"
LONGUSAGE="\t-h\tPrint this help message
\t-k\tKernel database (no system includes)
\t<directories>\tDirectories to scan (defaults to '.')"

source ${HOME}/bin/scripts/functions.sh

while getopts ":hk" option; do
	case ${option} in
		k ) KERNEL="-k";;
		h ) usage;;
		\? ) usage "Invalid argument ${OPTARG}";;
		* ) usage "Invalid argument ${option}";;
	esac
done

# Store how we got here, so vim can re-run the same arguments
echo "$0 $@" > ".#maketags.dfg"

# Get stuff from the .maketagsrc file
if [ -f "${HOME}/.maketagsrc" ]; then
	source ${HOME}/.maketagsrc
fi

if [ "${OPTIND}" != "0" ]; then
	shift $((OPTIND-1))
fi

if [ -z "$1" ]; then
	DIRS="."
else
	DIRS="$@"
fi

if [ -n "${KERNEL}" ]; then
	echo "Making kernel tags for $DIRS"
else
	echo "Making tags for $DIRS"
fi

TMPFILE=`mktemp -t maketags.XXXXXXXXXX` || die "Couldn't make tempfile"
find ${DIRS} -name "*.c" -or -name "*.cpp" -or -name "*.cxx" -or -name "*.h++" -or -name "*.hxx" -or -name "*.hh" -or -name "*.hpp" -or -name "*.H" -or -name "*.C" -or -name "*.c++" -or -name "*.cc" -or -name "*.h" >> ${TMPFILE}

if [ -n "${SKIPRE}" ]; then
	egrep -v "${SKIPRE}" ${TMPFILE} > cscope.files
else
	cp ${TMPFILE} cscope.files
fi
rm ${TMPFILE}
cscope -q -L ${KERNEL} -i cscope.files
exuberant-ctags -L- < cscope.files
