#!/bin/bash
#
# Setup a new account with the scripts.  To be run in the directory you want the scripts.
#
# Requires: git, sed
#

REPO="git://github.com/dang/scripts.git"

# Array formats are: array["<targetpath>"] = "<file> [<file>...]"
#  Each entry is found in $SCRIPTDIR/cfg/<targetpath>/<file> and is installed into ${HOME}/<targetpath>/<file>

# These are items that should be symlinked to the scripts dir, so they're always up-to-date.
declare -A LNSET=(
	["."]=".ackrc .atoolrc .bashrc .cvsrc .face .gdbinit .gitignore .gvimrc .inputrc .lesskey .nvimrc .profile .tigrc .tmux.conf .toprc .vim .vimrc .vrapperrc .xinitrc" 
	[".config"]="awesome luakit"
	[".config/xfce4"]="terminal"
)

# These are copied, so that they can be locally modified
declare -A CPSET=(
	["."]=".gitconfig"
	[".ssh"]="config"
	[".bashrc.d"]="00defaults  prompt  python-virtualenv  user-path"
)

WANTPROGS="atool tmux udiskie xclip xvkbd"

umask 0077

# if is_interactive; then echo "interactive" fi
#
# Check for an interactive shell
is_interactive() {
	case $- in
		*i*)
			# Don't die in interactive shells
			return 0
			;;
		*)
			return 1
			;;
	esac
}

# if can_die; then exit
#
# Check to see if it's legal to exit during die
can_die() {
	if (( BASH_SUBSHELL > 0 )); then
		return 0
	fi
	if ! is_interactive; then
		return 0
	fi
	return 1
}

# command | die "message"
#
# Print a message and exit with failure
die() {
	echo "Failed: $@"
	if [ ! -z "$(declare -F | grep "DFGcleanup")" ]; then
		DFGcleanup "$@"
	fi
	if can_die; then
		exit 1
	fi
}

function cmd_exists {
	which $1 > /dev/null 2>&1
	if [ "$?" == "1" ]; then
		die "You don't have $1 installed, sorry"
	fi
}

# checkexists ASSOC_ARRAY
#
# Check if the entries in the array exist
#
# Note: do *not* dereference the array in the call
function checkexists {
	local _str_arr="$(declare -p $1)"
	eval "local -A array=${_str_arr#*=}"
	(
	for k in "${!array[@]}"; do
		for f in ${array[$k]}; do
			local base="$k/$f"
			if [ "$k" == "." ]; then
				# no extra ./
				base="$f"
			fi
			[ -a "${HOME}/${base}" ] && die "${HOME}/${base} exists; not continuing"
		done
	done
	exit 0
	)
	return $?
}


# install ASSOC_ARRAY [$copy]
#
# Install the entries in the array.  If copy is given and not empty, copy them.
# Otherwise, symlink them
#
# Note: do *not* dereference the array in the call
function install {
	local _str_arr="$(declare -p $1)"
	eval "local -A array=${_str_arr#*=}"
	local copy=$2
	(
	for k in "${!array[@]}"; do
		for f in ${array[$k]}; do
			local base="$k/$f"
			if [ "$k" == "." ]; then
				# no extra ./
				base="$f"
			fi
			local basedir=$(dirname $base{})
			mkdir -p "${HOME}/${basedir}"
			if [ -z "${copy}" ]; then
				ln -s "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" || die "failed to link ${base}"
			else
				cp -a "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" || die "failed to copy ${base}"
			fi
		done
	done
	)
	return $?
}

cmd_exists sed

if [ -z "${1}" ]; then
	echo "no directory given"
	die "usage: scripts-setup <directory>"
fi

if [ "$1" == "." ]; then
	SCRIPTDIR=${PWD}
else
	SCRIPTDIR=$1
fi

# Check for conflicts
checkexists LNSET || die "Not overriting symlink files"
checkexists CPSET || die "Not overriting copy files"

if [ ! -d "${SCRIPTDIR}/.git" ]; then
	SAVEDIR=${PWD}
	cmd_exists git
	cd $(dirname "${SCRIPTDIR}")
	git clone ${REPO} $(basename ${SCRIPTDIR})
	cd $(basename "${SCRIPTDIR}")
	git submodule update --init --recursive
	cd "${SAVEDIR}"
fi
if [ ! -d "${SCRIPTDIR}/.git" ]; then
	echo "Failed to clone scripts repo from ${REPO}"
	exit 2
fi

cd ${HOME}
# Set up .scripts symlink
ln -s ${SCRIPTDIR} .scripts
if [ -h "${SCRIPTDIR}/.scripts" ]; then
	# installed into .scripts; remove extra symlink
	rm "${SCRIPTDIR}/.scripts"
fi

# Install files
install LNSET || die "Failed to install symlink files"
install CPSET "copy" || die "Failed to install copy files"

# Set up less
lesskey

# Look to see if my desired programs are installed
for i in ${WANTPROGS}; do
	which $i > /dev/null 2>&1
	if [ "$?" == "1" ]; then
		NEEDPROGS="$i ${NEEDPROGS}"
	fi
done

echo "Done."
echo "You need to edit ${HOME}/.bashrc.d/* for your your local settings"
if [ -n "${NEEDPROGS}" ]; then
	echo "Please install ${NEEDPROGS}"
fi
