#!/bin/bash
#
# Setup a new account with the scripts.  To be run in the directory you want the scripts.
#
# Requires: git, sed
#

REPO="git://github.com/dang/scripts.git"
LNFILES="ackrc atoolrc bashrc cvsrc face gitignore gvimrc inputrc lesskey profile tigrc tmux.conf vim vimrc vrapperrc xinitrc"
CPFILES="gitconfig"
CFGDIRS="awesome luakit xfce4/terminal"
WANTPROGS="atool tmux udiskie xclip xvkbd"

function die {
	echo "$@"
	exit 1
}

function cmd_exists {
	which $1 > /dev/null 2>&1
	if [ "$?" == "1" ]; then
		die "You don't have $1 installed, sorry"
	fi
}

cmd_exists sed

if [ -z "${1}" ]; then
	echo "no directory given"
	die "usage: scripts-setup <directory>"
fi

if [ "$1" == "." ]; then
	SCRIPTDIR=${PWD}
else
	SCRIPTDIR=$1
fi

# Make config dir
mkdir -p "${HOME}/.config"

# Check for conflicts
for i in ${LNFILES}; do
	[ -a "${HOME}/.${i}" ] && die "${HOME}/.${i} exists; not continuing"
done
for i in ${CFGDIRS}; do
	[ -a "${HOME}/.config/${i}" ] && die "${HOME}/.config/${i} exists; not continuing"
done
[ -a "${HOME}/.bashrc.d" ] && die "${HOME}/.bashrc.d exists; not continuing"

if [ ! -d "${SCRIPTDIR}/.git" ]; then
	SAVEDIR=${PWD}
	cmd_exists git
	cd $(dirname "${SCRIPTDIR}")
	git clone ${REPO} $(basename ${SCRIPTDIR})
	cd $(basename "${SCRIPTDIR}")
	git submodule update --init --recursive
	cd "${SAVEDIR}"
fi
if [ ! -d "${SCRIPTDIR}/.git" ]; then
	echo "Failed to clone scripts repo from ${REPO}"
	exit 2
fi

cd ${HOME}
# Set up .scripts symlink
ln -s ${SCRIPTDIR} .scripts
if [ -h "${SCRIPTDIR}/.scripts" ]; then
	# installed into .scripts; remove extra symlink
	rm "${SCRIPTDIR}/.scripts"
fi

mkdir -p "${HOME}/.bashrc.d"
cp -a "${SCRIPTDIR}/bashrc.d/local/"* "${HOME}/.bashrc.d"

for FILE in ${CPFILES}; do
	[ -a ".${FILE}" ] || cp ".scripts/cfg/.${FILE}" "${HOME}/.${FILE}"
done
for FILE in ${LNFILES}; do
	ln -s "${HOME}/.scripts/cfg/.${FILE}" "${HOME}/.${FILE}"
done
for DIR in ${CFGDIRS}; do
	BASEDIR=$(dirname $DIR{})
	mkdir -p "${HOME}/.config/${BASEDIR}"
	ln -s "${HOME}/.scripts/cfg/.config/${DIR}" "${HOME}/.config/${DIR}"
done

# Set up less
lesskey

# Look to see if my desired programs are installed
for i in ${WANTPROGS}; do
	which $i > /dev/null 2>&1
	if [ "$?" == "1" ]; then
		NEEDPROGS="$i ${NEEDPROGS}"
	fi
done

echo "Done."
echo "You need to edit ${HOME}/.bashrc.d/* for your your local settings"
if [ -n "${NEEDPROGS}" ]; then
	echo "Please install ${NEEDPROGS}"
fi
