#!/bin/bash
#
# Fix scripts after reorganization
#
# Requires: git, sed
#

REPO="git://github.com/dang/scripts.git"
LNFILES="ackrc atoolrc bashrc cvsrc face gdbinit gitignore gvimrc inputrc lesskey nvimrc profile tigrc tmux.conf toprc vim vimrc vrapperrc xinitrc"
CFGDIRS="awesome luakit xfce4/terminal"

function die {
	echo "$@"
	exit 1
}

function cmd_exists {
	which $1 > /dev/null 2>&1
	if [ "$?" == "1" ]; then
		die "You don't have $1 installed, sorry"
	fi
}

for FILE in ${LNFILES}; do
	rm -f ".${FILE}" && ln -s "${HOME}/.scripts/cfg/.${FILE}" "${HOME}/.${FILE}"
done
for DIR in ${CFGDIRS}; do
	rm -f "${HOME}/.config/${DIR}" && ln -s "${HOME}/.scripts/cfg/.config/${DIR}" "${HOME}/.config/${DIR}"
done

echo "Fixed."
