#!/bin/bash
#
# Script that blames a file
#

# Set usage output
USAGE="[-h |--help] [-l <line> | --line=<number>] [-t <tag> | --tag=<tag>] [-p <path> | --path=<path>] [<file>]"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t-l <line>, --line=<number>\n\t\tLook up version at <number> and print it's info
\t-t <tag>, --tag=<tag>\n\t\tUse speecified tag
\t-p <path>, --path=<path>\n\t\tUse <path> as the working dir (default: .)
\t<file>\n\t\tFile to annotate"

# Standard functions
source ${SCRIPTS}/functions.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o hl:p:t: --long help,line:,path:,tag: -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		-l|--line) LINE=$2 ; shift 2 ;;
		-t|--tag) TAG=$2 ; shift 2 ;;
		-p|--path) BASEPATH=$2 ; shift 2 ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal

if [ -z "$1" ]; then
	usage
fi

if [ -n "${BASEPATH}" ]; then
	cd "${BASEPATH}" || die "failed to CD to ${BASEPATH}"
fi

vcs_detect

vcs_blame $1 $LINE

