#!/bin/bash
#

# fvwm
# setxkbmap us -variant colemak
# ck-launch-session gnome-session

#
# awesome

# eval $(dbus-launch --exit-with-session --sh-syntax)
# /usr/libexec/gconfd-2 &
# /usr/libexec/gnome-settings-daemon &

# eval $(/usr/bin/gnome-keyring-daemon)
# export GNOME_KEYRING_SOCKET
# export SSH_AUTH_SOCK
# export GNOME_KEYRING_PID

# /usr/libexec/gnome-volume-manager &
# /usr/bin/gnome-power-manager &
# #ck-launch-session &
# #nm-applet &
# nautilus --no-default-window &
# awesome > output.dfg 2>&1

#
# GNOME
#

## Source scripts in /etc/X11/xinit/xinitrc.d/
#if [ -d /etc/X11/xinit/xinitrc.d ]; then
	#for f in /etc/X11/xinit/xinitrc.d/*; do
		#[ -x "$f" ] && . "$f"
	#done
	#unset f
#fi

#setxkbmap us -variant colemak
#/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
##/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#eval $(/usr/bin/gnome-keyring-daemon)
#export GNOME_KEYRING_SOCKET
#export GNOME_KEYRING_PID
#export GNOME_KEYRING_CONTROL
#export SSH_AUTH_SOCK
#export GPG_AGENT_INFO

#nm-applet &

#exec awesome > awesome.log 2>&1
##exec awesome

#
# XFCE4

setxkbmap us -variant colemak
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(/usr/bin/gnome-keyring-daemon)
export GNOME_KEYRING_SOCKET
export GNOME_KEYRING_PID
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

xfce4-power-manager &

exec startxfce4
#nm-applet &
#exec awesome
